import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Printer, Share2, Brain, Activity, ShieldCheck, User } from 'lucide-react';
import GlassCard from '@/components/medical/GlassCard';

export default function Reports() {
  return (
    <div className="p-8 space-y-8 min-h-screen bg-[#050B1A] text-white">
      <div className="flex justify-between items-end">
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-4xl font-bold mb-2 flex items-center gap-3">
            <FileText className="w-10 h-10 text-cyan-400" />
            Clinical Reports
          </h1>
          <p className="text-gray-400">Comprehensive patient monitoring and AI diagnostic reports</p>
        </motion.div>
        
        <div className="flex gap-4">
          <button className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-gray-300 transition-colors">
            <Printer className="w-4 h-4" /> Print
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-gray-300 transition-colors">
            <Share2 className="w-4 h-4" /> Share
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-cyan-600 hover:bg-cyan-500 rounded-lg text-white font-medium transition-colors shadow-lg shadow-cyan-900/20">
            <Download className="w-4 h-4" /> Export PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Report List Sidebar */}
        <div className="space-y-4">
          <h3 className="font-bold text-gray-400 mb-4 uppercase tracking-wider text-sm">Recent Reports</h3>
          
          {[
            { id: 'REP-001', name: 'Patient JD-042 Session', date: 'Oct 24, 2026', type: 'Seizure Event', active: true },
            { id: 'REP-002', name: 'Patient AK-119 Baseline', date: 'Oct 23, 2026', type: 'Routine', active: false },
            { id: 'REP-003', name: 'Cohort Alpha Validation', date: 'Oct 20, 2026', type: 'LOSO Validation', active: false },
            { id: 'REP-004', name: 'Patient JD-042 Sleep', date: 'Oct 18, 2026', type: 'Overnight', active: false },
          ].map((rep) => (
            <div key={rep.id} className={`p-4 rounded-xl border cursor-pointer transition-all ${rep.active ? 'bg-cyan-900/20 border-cyan-500/40 border-l-4 border-l-cyan-400' : 'bg-slate-900/50 border-slate-800 hover:border-slate-600'}`}>
              <div className="flex justify-between items-start mb-1">
                <span className={`text-sm font-bold ${rep.active ? 'text-white' : 'text-gray-300'}`}>{rep.name}</span>
                <span className="text-[10px] text-gray-500">{rep.date}</span>
              </div>
              <div className="flex items-center gap-2 mt-2">
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-800 text-gray-400">{rep.id}</span>
                <span className={`text-[10px] px-2 py-0.5 rounded-full ${rep.type === 'Seizure Event' ? 'bg-red-900/30 text-red-400' : 'bg-slate-800 text-gray-400'}`}>{rep.type}</span>
              </div>
            </div>
          ))}
        </div>

        {/* Report Preview */}
        <div className="lg:col-span-2">
          <GlassCard hover={false} className="h-full">
            <div className="border-b border-slate-700/50 pb-6 mb-6">
              <div className="flex justify-between items-start">
                <div>
                  <h2 className="text-2xl font-bold text-white mb-2">Automated EEG Diagnostic Report</h2>
                  <p className="text-gray-400 text-sm">Generated by NeuroWatch AI Pipeline v2.4</p>
                </div>
                <div className="text-right">
                  <div className="text-cyan-400 font-mono text-lg">JD-042</div>
                  <div className="text-gray-500 text-xs mt-1">Oct 24, 2026 - 14:32 PST</div>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-6 mb-8">
              <div className="space-y-4">
                <div className="flex items-center gap-3">
                  <User className="w-5 h-5 text-gray-400" />
                  <div>
                    <div className="text-xs text-gray-500 uppercase">Patient Profile</div>
                    <div className="font-medium text-gray-200">John Doe, 42 Yrs, Male</div>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Activity className="w-5 h-5 text-gray-400" />
                  <div>
                    <div className="text-xs text-gray-500 uppercase">Recording Duration</div>
                    <div className="font-medium text-gray-200">4 Hours 12 Minutes</div>
                  </div>
                </div>
              </div>
              
              <div className="p-4 bg-red-900/10 border border-red-900/30 rounded-lg">
                <h4 className="text-red-400 font-bold mb-1 flex items-center gap-2">
                  <ShieldCheck className="w-5 h-5" /> Primary Finding
                </h4>
                <p className="text-sm text-red-200/80">Ictal event detected at 15:42 (Duration: 42s). High risk preictal patterns observed 12 minutes prior to onset in temporal regions (T3, T4).</p>
              </div>
            </div>

            <div className="space-y-6">
              <div className="border border-slate-700 rounded-lg p-5">
                <h4 className="font-bold text-cyan-400 mb-4 flex items-center gap-2"><Brain className="w-5 h-5" /> AI Prediction Summary</h4>
                <div className="grid grid-cols-3 gap-4">
                  <div className="bg-slate-900/50 p-3 rounded">
                    <div className="text-xs text-gray-500 mb-1">Seizure Probability</div>
                    <div className="text-xl font-bold text-red-400">92.4%</div>
                  </div>
                  <div className="bg-slate-900/50 p-3 rounded">
                    <div className="text-xs text-gray-500 mb-1">AI Confidence</div>
                    <div className="text-xl font-bold text-emerald-400">High (0.96)</div>
                  </div>
                  <div className="bg-slate-900/50 p-3 rounded">
                    <div className="text-xs text-gray-500 mb-1">Dominant Channels</div>
                    <div className="text-xl font-bold text-cyan-400 font-mono">T3, F7</div>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-bold text-gray-300 mb-3">Clinical Notes</h4>
                <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700 text-sm text-gray-400 min-h-[100px]">
                  Automated analysis suggests right temporal lobe anomaly preceding the event. AI feature analysis indicates strong dependency on high-frequency gamma band activity. Recommend physician review of epoch 442-458.
                </div>
              </div>
            </div>
            
          </GlassCard>
        </div>
      </div>
    </div>
  );
}
